apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbit
spec:
  replicas: 1   # ✅ 하나만 띄우는 설정
  service:
    type: ClusterIP
  persistence:
    storageClassName: standard
    storage: "1Gi"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
  rabbitmq:
    additionalConfig: |
      default_user = admin
      default_pass = admin

---
apiVersion: v1
kind: Service
metadata:
  name: my-rabbit-ui
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: my-rabbit
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31567  # 외부에서 접속할 포트